# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52661768183bd0b510fb0ebc448998ff8d18ede1f61d3f0f751c5b00c9b0dac14f37baac1c02703e7c575edecff1c6f2a9c8b434cc52c08cdc9643909815273c

test:
  secret_key_base: 3edfda517a3b09e9d3211f837c9003ecc52a3ecf805d612a840046513d3fcf000a568c8b5f0d44138970b51117ac2728ea7e8f616cb2a292025efe2457a0a35f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
